language: java
jdk:
  - oraclejdk8

sudo: false

install: true

script:
  - pwd

after_success:
  - pwd
  - ls -al
  - mkdir lambda_artifact
  - zip -r lambda-${TRAVIS_JOB_NUMBER}.zip /build/libs/ROOT.war
  - ls -al
  - mv lambda-${TRAVIS_JOB_NUMBER}.zip lambda_artifact/
  - ls -al
  - pwd
  - cd lambda_artifact
  - ls -al
  - aws lambda update-function-code --function-name MyLambdaFunction --zip-file fileb://lambda-${TRAVIS_JOB_NUMBER}.zip --s3-bucket $s3_bucket
  - ls -al
  
deploy:
  - provider: s3
    local_dir: lambda_artifact
    bucket: $s3_bucket
    region: us-east-1
    skip_cleanup: true
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    on:
      branch: assignment07-08
